# Generated by Django 5.1.3 on 2024-12-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('como_obtener', models.TextField()),
                ('imagen', models.ImageField(upload_to='logros/')),
                ('puntos', models.IntegerField()),
            ],
        ),
    ]
