# Generated by Django 4.2.16 on 2024-11-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_usuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='info_usuario',
            name='objetivo_calorico_diario',
        ),
    ]
