# Generated by Django 5.1.3 on 2024-11-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_usuarios', '0002_remove_info_usuario_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_usuario',
            name='comidas_dia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info_usuario',
            name='litros_dia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info_usuario',
            name='preferencias_alimentarias',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
