# Generated by Django 5.1.3 on 2024-12-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_usuarios', '0003_info_usuario_comidas_dia_info_usuario_litros_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_usuario',
            name='nivel_actividad',
            field=models.IntegerField(max_length=50),
        ),
    ]
