# Generated by Django 5.1.3 on 2024-12-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_usuarios', '0004_alter_info_usuario_nivel_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_usuario',
            name='nivel_actividad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info_usuario',
            name='peso',
            field=models.IntegerField(),
        ),
    ]
