# Generated by Django 4.2.16 on 2024-12-03 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vasos', models.IntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetaNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias_diarias', models.IntegerField(default=2000)),
                ('carbohidratos_diarios', models.IntegerField(default=250)),
                ('proteinas_diarias', models.IntegerField(default=60)),
                ('grasas_diarias', models.IntegerField(default=70)),
                ('vasos_agua', models.IntegerField(default=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='waterintake',
            name='user',
        ),
        migrations.DeleteModel(
            name='NutritionGoal',
        ),
        migrations.DeleteModel(
            name='WaterIntake',
        ),
    ]
